// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHbnoyjfdGDL3YnK12yYtLqQ_hwH8aen0',
    appId: '1:576042190463:web:4926bd5c71636d0019a14a',
    messagingSenderId: '576042190463',
    projectId: 'flutter-first-project-464d4',
    authDomain: 'flutter-first-project-464d4.firebaseapp.com',
    storageBucket: 'flutter-first-project-464d4.firebasestorage.app',
    measurementId: 'G-Z11T5KLWG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApFWVQmwtQi7jQj_TAMHo5L2cilX4a5qQ',
    appId: '1:576042190463:android:8033606983ec5c3f19a14a',
    messagingSenderId: '576042190463',
    projectId: 'flutter-first-project-464d4',
    storageBucket: 'flutter-first-project-464d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJB7Wa93_0mJ8ORsxhmsXFr8hNXkqKpZc',
    appId: '1:576042190463:ios:d8eedaf68aed94cb19a14a',
    messagingSenderId: '576042190463',
    projectId: 'flutter-first-project-464d4',
    storageBucket: 'flutter-first-project-464d4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2Dars',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJB7Wa93_0mJ8ORsxhmsXFr8hNXkqKpZc',
    appId: '1:576042190463:ios:d8eedaf68aed94cb19a14a',
    messagingSenderId: '576042190463',
    projectId: 'flutter-first-project-464d4',
    storageBucket: 'flutter-first-project-464d4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2Dars',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHbnoyjfdGDL3YnK12yYtLqQ_hwH8aen0',
    appId: '1:576042190463:web:31bba1826a62f20219a14a',
    messagingSenderId: '576042190463',
    projectId: 'flutter-first-project-464d4',
    authDomain: 'flutter-first-project-464d4.firebaseapp.com',
    storageBucket: 'flutter-first-project-464d4.firebasestorage.app',
    measurementId: 'G-GWPKNY61M8',
  );
}
